# Generated by Django 6.0.6 on 2026-06-23 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(default='Produto sem descrição', max_length=320, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('image_path', models.URLField(blank=True, null=True, verbose_name='Caminho da Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('crop_x', models.IntegerField(blank=True, null=True, verbose_name='Eixo x')),
                ('crop_y', models.IntegerField(blank=True, null=True, verbose_name='Eixo y')),
                ('crop_width', models.IntegerField(blank=True, null=True, verbose_name='Corte Largura')),
                ('crop_height', models.IntegerField(blank=True, null=True, verbose_name='Corte Altura')),
                ('category', models.ManyToManyField(related_name='products', to='categories.category', verbose_name='Categorias')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
