# Generated by Django 6.0.6 on 2026-06-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da casa')),
                ('coins', models.IntegerField(blank=True, null=True, verbose_name='Moedas de troca')),
                ('premium', models.BooleanField(default=False, verbose_name='Cliente Premium')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Avatar URL')),
                ('avatar_path', models.URLField(blank=True, null=True, verbose_name='Avatar Caminho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
